// Generated by https://quicktype.io

export interface DashboardSummaryResponse {
    numberOfOrders: number;
    payOrders: number;
    notPaidOrders: number;
    numberOfClients: number;
    numberOfProducts: number;
    productsWithNoInventory: number;
    lowInventory: number;
}
